#!/usr/bin/env python3
"""gen_docs.py - Regenerate the machine-derived documentation:
  docs/NETLIST.md          every net: KiCad name, Allegro name, pins (ref-pin/pin name), sheet, V1 note, "changed in V2?"
  docs/CONVERSION_NOTES.md the generated footprint-mapping table (between markers; prose around it is hand-written)
  docs/INDEX.md            one table linking every document and image with a one-line purpose
Inputs: hardware/kicad/_build/{v5_board,netmap,footprint_table,mpn,netlist_check,xor_report,drc,erc}.json, docs/img/*
Run from repo root: python hardware/kicad/tools/gen_docs.py
"""
import os, sys, json, glob, collections
HERE = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, HERE)
ROOT = os.path.abspath(os.path.join(HERE, '..', '..', '..'))
KDIR = os.path.join(ROOT, 'hardware', 'kicad'); BUILD = os.path.join(KDIR, '_build'); DOCS = os.path.join(ROOT, 'docs')
import allegro_data as ad
from v1_design import SHEET_OF, kicad_ref

# Human notes per KiCad net (V1 as built) and V2 disposition.  Anything not listed: "unchanged".
NET_NOTES = {
    'GND': ('Bottom-layer pour; top pour is +3V3', 'kept; V2 adds proper star/return for the actuator rail'),
    '+3V3': ('Top-layer pour. Also feeds SPEEDCONTROLLER-1 and STEERINGSERVO-1 (actuator power pins!) and JTAG-1', 'V2: actuator power leaves this rail'),
    'VIN_RAW': ('Battery pad, CIN, U6 VIN, R4 (CE pull-up), R5 (ADC divider); no fuse / reverse protection / TVS', 'V2: fuse + reverse-polarity + TVS + bulk cap'),
    'SW_NODE': ('U6 LX, L1-2, C12-1 (bootstrap RC), D21-2 cathode of the CMS06 catch diode', 'unchanged topology; layout tightened'),
    'BST': ('U6 BST to R3 (51 R)', 'unchanged'), 'BST_RC': ('between R3 and C12 (0.1 uF) - the bootstrap RC per Nisshinbo DS', 'unchanged'),
    'EN': ('U6 CE via R4 5.1 k from VIN_RAW (CE has no internal pull)', 'V2: MCU-controlled enable optional'),
    'FB_DIV': ('U6 VFB with R1 15 k / R2 4.7 k / C14 470 pF -> Vout = 0.8*(1+15/4.7) = 3.35 V', 'unchanged'),
    'ADC_VBAT': ('R5 30 k / R6 10 k divider to PA2 (ADC1_IN2); firmware never enables the ADC', 'V2: read it; add filter cap'),
    'VCAP1': ('U3 pin 30 VCAP_1 to CEXT-1; CEXT-2 returns to +3V3 instead of VSS (V1 defect)', 'V2: 4.7 uF to VSS'),
    'LORA_VCC': ('LoRa header VDD after ferrite L3, with C21 10 uF, C22 0.1 uF, C23 (22 or 47 pF) to GND', 'V2: same filter, verify TX current'),
    'LORA_FILT': ('between L4 (from +3V3) and L3; C20 10 uF to +3V3 (not GND!)', 'V2: cap to GND'),
    'LORA_TX_PA0': ('UART4_TX -> LoRa RXD', 'series resistor in V2'), 'LORA_RX_PA1': ('LoRa TXD -> UART4_RX', 'series resistor in V2'),
    'LORA_RST_PA3': ('PA3 -> LoRa NRST; firmware never drives it', 'V2 firmware drives reset'),
    'GPS_PB0': ('PB0 GPIO output (held LOW by firmware) -> GPS header pin 3', 'V2: PPS input instead'),
    'GPS_RX_PC11': ('GPS TXD -> USART3_RX', 'unchanged'), 'GPS_TX_PC10': ('USART3_TX -> GPS RXD (also carries debug prints)', 'V2: separate console'),
    'CAN_STB_PA11': ('PA11 (= CAN1_RX pin!) drives U5 STB', 'V2: STB on a plain GPIO or tied low'),
    'CAN_RXD_PA10': ('U5 RXD -> PA10, which has no CAN alternate function', 'V2: RXD to PA11'),
    'CAN_TXD_PA12': ('PA12 CAN1_TX -> U5 TXD (correct)', 'unchanged'),
    'CANH': ('U5 pin 7 (CANH) -> CANHEADER pin 3', 'V2: termination option'), 'CANL': ('U5 pin 6 (CANL) -> CANHEADER pin 4', 'V2: termination option'),
    'CAN_VCC': ('U5 VCC (needs 4.5-5.5 V) supplied from CANHEADER-2, C1 0.1 uF', 'V2: on-board 5 V'),
    'PWM_PA8_ESCHDR': ('PA8/TIM1_CH1 -> SPEEDCONTROLLER-2 (and TP1); firmware calls PA8 "rudder"', 'V2: named by function, series R + ESD'),
    'PWM_PC6_SERVOHDR': ('PC6/TIM3_CH1 -> STEERINGSERVO-2 (and TP3); firmware calls PC6 "motor"', 'V2: named by function, series R + ESD'),
    'SWDIO': ('PA13 -> JTAG-2', 'unchanged'), 'SWCLK': ('PA14 -> JTAG-4', 'unchanged'), 'SWO_TDO': ('PB3 -> JTAG-6', 'unchanged'),
    'TDI': ('PA15 -> JTAG-8', 'V2: SWD only, free PA15/PB3'), 'NRST': ('U3 NRST -> JTAG-10; no external RC', 'V2: 100 nF on NRST'),
    'VBAT': ('U3 pin 1 only - floating on V1', 'V2: tie to VDD'),
}

def netlist_md():
    b = json.load(open(os.path.join(BUILD, 'v5_board.json')))
    netmap = json.load(open(os.path.join(BUILD, 'netmap.json')))
    nets = ad.load_pstxnet()
    lines = ['# NETLIST - LoRa Autonomous Boat Controller V1 (as fabricated)', '',
             'Generated by `hardware/kicad/tools/gen_docs.py` from `pstxnet.dat` (OrCAD packaging of 2025-05-09 17:12, imported into senior design v5.brd) and the KiCad netmap. '
             'Do not edit by hand. KiCad references carry a `1` suffix where the Allegro refdes had no trailing digit (e.g. `CANHEADER1` = Allegro `CANHEADER`).', '',
             f'{len(nets)} nets ({sum(1 for v in nets.values() if len(v) > 1)} with two or more pins, {sum(1 for v in nets.values() if len(v) == 1)} single-node) plus 37 unconnected (NC) pins. '
             'The schematic and board were proven to carry exactly these pin sets by `check_netlist.py` (see `hardware/kicad/_build/netlist_check.json`).', '',
             '| KiCad net | Allegro net | Pins | Sheet(s) | V1 note (as built) | Changed in V2? |', '|---|---|---|---|---|---|']
    for aname, pins in sorted(nets.items(), key=lambda kv: (kv[0] not in ('0', '3.3V'), netmap.get(kv[0], kv[0]))):
        kname = netmap.get(aname, aname)
        pinstr = ', '.join(f'{kicad_ref(r)}-{p}' + (f' ({n})' if n and n != p else '') for r, p, n in pins)
        sheets = sorted({SHEET_OF[r] for r, p, n in pins if r in SHEET_OF})
        note, v2 = NET_NOTES.get(kname, ('', 'unchanged'))
        lines.append(f'| `{kname}` | `{aname}` | {pinstr} | {", ".join(sheets)} | {note} | {v2} |')
    nc = [f'U3-{p}' for p in ['2','3','4','5','6','8','9','10','11','20','21','22','23','24','25','27','28','29','33','34','35','36','38','39','40','42','53','54','56','57','58','59','60','61','62']] + ['U5-5', 'JTAG1-7']
    lines += ['', '## Unconnected pins (NC in pstxnet.dat)', '', 'U3: ' + ', '.join(p for p in nc if p.startswith('U3')) + ' (35 MCU pins incl. BOOT0 pin 60 and the HSE/LSE pins 3, 4, 5, 6); U5-5 (NC on the H variant); JTAG1-7 (key).', '',
              '## Reading the names', '',
              '- Signal nets are named by MCU pin so the PWM swap question cannot recur: `PWM_PA8_ESCHDR` reaches the header the silkscreen calls SPEEDCONTROLLER, `PWM_PC6_SERVOHDR` the STEERINGSERVO header.',
              '- `CANL`/`CANH` follow the TCAN1042H pin functions (pin 6 = CANL, pin 7 = CANH); the March 2026 NETLIST.md had them reversed.',
              '- Power symbols in the schematic: `GND`, `+3V3`, `VIN_RAW`.']
    open(os.path.join(DOCS, 'NETLIST.md'), 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')

def footprint_table_md():
    t = json.load(open(os.path.join(BUILD, 'footprint_table.json')))
    rows = ['| Allegro footprint (JEDEC_TYPE) | Project footprint | Used by | Pads (mil, as fabricated) | Nearest KiCad-library footprint | Pad delta vs library |', '|---|---|---|---|---|---|']
    DELTA = {
        'LQFP64-10x10mm': '47x12 mil pads vs 1.5x0.3 mm (59x11.8): fab pads are 12 mil shorter',
        'D0008A_L': 'oblong 21.65x49.21 mil at 50 mil pitch vs SOIC-8 lib 1.55x0.6 mm rect',
        'SOT-23-6W_PE-SOT23-6W-0512_NMD': '35.5x22 mil vs lib 1.06x0.65 mm (41.7x25.6)',
        'CAP_KGM21_KAV-L': '36x47 mil at 55 mil pitch vs 0805 lib 1.0x1.45 mm at 1.9 mm (39x57 at 75)',
        'IND_7045_TDK': 'custom 86.6x94.9 mil pads at 216 mil pitch; TDK recommends 2.2x1.5 mm at 6.3 mm',
        'M-FLAT_TOS-L': '71x38 mil at 163 mil pitch; Toshiba recommends 2.1x1.4 mm at 4.4 mm (173 mil)',
        'SAMTEC_FTSH-105-XX-X-DV': '29.13x109.84 mil = Samtec 0.029x0.110 in; row spacing 160.24 mil = 0.160 in',
        'CAP_NTS_55_2P8T_NIP': '65x213 mil at 203 mil pitch for the 5.7x5.0 mm Chemi-Con NTS body',
        'amv_test_point': '133.86 mil (3.4 mm) pad, 55.12 mil (1.4 mm) hole', 'amv_con1': '62.99 mil (1.6 mm) pad, 23.62 mil (0.6 mm) hole',
        'CONN5_1LFBN-RC_SUL': '68 mil pad / 40 mil hole (DSN v2 had 60/40)', 'CONN_PPTC031_SUL': '68 mil pad / 40 mil hole (DSN v2 had 60/40)',
        'CONN_B4B-XH-A_JST': '69 mil pad / 49 mil hole at 98.42 mil (2.5 mm) pitch',
    }
    for e in t:
        pads = e['pads']
        if len(pads) <= 4:
            pd = '; '.join(f"{p['n']}: {p['shape']} {p['w']:g}x{p['h']:g}@({p['x']:g},{p['y']:g})" + (f" hole {p['hole']:g}" if p['hole'] else '') for p in pads)
        else:
            p = pads[0]; pd = f"{len(pads)} pads {p['shape']} {p['w']:g}x{p['h']:g}" + (f" hole {p['hole']:g}" if p['hole'] else '')
        rows.append(f"| `{e['jedec']}` | `{e['kicad']}` | {', '.join(kicad_ref(r) for r in e['used_by'])} | {pd} | `{e['nearest_std']}` | {DELTA.get(e['jedec'], 'same package class; pad sizes differ by a few mil')} |")
    path = os.path.join(DOCS, 'CONVERSION_NOTES.md')
    B, E = '<!-- BEGIN GENERATED gen_docs.py footprints -->', '<!-- END GENERATED gen_docs.py footprints -->'
    md = open(path, encoding='utf-8').read() if os.path.exists(path) else '# Allegro -> KiCad conversion notes\n\n' + B + '\n' + E + '\n'
    body = '\n'.join(rows)
    if B in md and E in md:
        pre, rest = md.split(B, 1); _, post = rest.split(E, 1); md = pre + B + '\n' + body + '\n' + E + post
    else:
        md += '\n\n## Footprint mapping (generated)\n\n' + B + '\n' + body + '\n' + E + '\n'
    open(path, 'w', encoding='utf-8', newline='\n').write(md)

def index_md():
    entries = [
        ('../README.md', 'Start here: what the system is, V1 -> V2 story, file map, how to open and regenerate everything'),
        ('../REPORT.md', 'The five-minute report: fidelity numbers, findings, V2 in one page, decisions needed, reproduction, session log'),
        ('../CONVERSION_LOG.md', 'Append-only work log of the reconstruction (dates, validations, commits)'),
        ('../BLOCKERS.md', 'Decisions Jay needs to make, with the defaults being used meanwhile'),
        ('../PROMPT_FOR_CODEX.md', 'Working brief for the second (review/documentation) agent'),
        ('A0_PROVENANCE.md', 'Which artwork is the fabricated v5 board, coordinate frames, placement v2 -> v5 diff, drill provenance, Gerber XOR tables'),
        ('V1_DESIGN_REVIEW.md', 'Every V1 finding with evidence, severity and V2 disposition; link budget, control-loop and power analysis'),
        ('V2_REQUIREMENTS.md', 'Numbered, testable V2 requirements (REQ-RF/CTL/PWR/NAV/DBG/MECH) and the decision list'),
        ('NETLIST.md', 'Every net: KiCad name, Allegro name, pin list, V1 note, changed-in-V2 column (generated)'),
        ('CONVERSION_NOTES.md', 'Allegro -> KiCad method, footprint mapping table (generated), what was substituted and why'),
        ('BOM.csv', 'V1 bill of materials with MPN, manufacturer, description, confidence and qty-1 price (generated)'),
        ('research/DATASHEET_NOTES.md', 'Cited datasheet facts for every active part and the LoRa modules'),
        ('research/BOM_MPN_RESEARCH.md', 'Part-number research with distributor prices and obsolescence notes'),
        ('research/FIRMWARE_REVIEW_NOTES.md', 'Line-cited firmware review (failsafe, UART, GPS, clocks, defect list)'),
        ('archive/STATUS.md', 'Superseded March-2026 pipeline status (archived)'),
        ('archive/SESSION_HANDOFF.md', 'Superseded March-2026 session handoff (archived)'),
        ('archive/DIRECTIVES.md', 'Superseded March-2026 CC/CD directive template (archived)'),
        ('../reviews/codex/README.md', 'Independent review packet by the Codex agent (assessment, platform concept, source audit)'),
    ]
    rows = ['# Documentation index', '', 'Generated by `hardware/kicad/tools/gen_docs.py`. Paths are relative to `docs/`.', '', '| Document | Purpose |', '|---|---|']
    for p, why in entries:
        if os.path.exists(os.path.join(DOCS, p)):
            rows.append(f'| [{p}]({p}) | {why} |')
    rows += ['', '## Images (docs/img)', '', '| Image | Purpose |', '|---|---|']
    IMGW = {
        'v1_pcb_top.png': 'KiCad raytraced render of the reconstructed V1 board, top', 'v1_pcb_bottom.png': 'KiCad raytraced render, bottom',
        'v1_schematic.pdf': 'All V1 schematic sheets (PDF)', 'v1_evidence_pwm.png': 'Copper evidence: PA8 -> SPEEDCONTROLLER, PC6 -> STEERINGSERVO',
        'v1_evidence_vcap.png': 'Copper evidence: CEXT between VCAP_1 (pin 30) and +3V3', 'v1_evidence_can.png': 'Copper evidence: PA12 -> TXD, PA11 -> STB, PA10 -> RXD',
    }
    for f in sorted(glob.glob(os.path.join(DOCS, 'img', '*'))):
        n = os.path.basename(f)
        if os.path.isdir(f):
            continue
        why = IMGW.get(n)
        if why is None:
            if n.startswith('v1_xor_dsn2'): why = 'DSN v2 copper vs v5 film (blue = DSN only, red = film only)'
            elif n.startswith('v1_xor_'): why = 'Fabrication film vs KiCad export XOR (red = film only, blue = KiCad only)'
            elif n.startswith('v1_fab_'): why = 'Rasterized fabrication film'
            elif n.startswith('v1_kicad_'): why = 'Rasterized KiCad Gerber export'
            elif n.startswith('v1_layer_'): why = 'KiCad layer export (SVG)'
            elif n.startswith('v1_sch_'): why = 'V1 schematic sheet (SVG)'
            elif n.startswith('v2_'): why = 'V2 design image'
            else: why = ''
        rows.append(f'| [{n}](img/{n}) | {why} |')
    open(os.path.join(DOCS, 'INDEX.md'), 'w', encoding='utf-8', newline='\n').write('\n'.join(rows) + '\n')

def main():
    netlist_md(); footprint_table_md(); index_md()
    print('wrote docs/NETLIST.md, docs/CONVERSION_NOTES.md (table), docs/INDEX.md')

if __name__ == '__main__':
    main()
